name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Geode-solutions/actions/.github/workflows/py-deploy.yml@master
    with:
      repos: ${{ vars.REPOS }}
      docker: true
      node: true
    secrets: inherit
