name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Geode-solutions/actions/.github/workflows/py-deploy.yml@master
    with:
      python: true
      docker: true
      npm: true
    secrets: inherit
